#!/bin/bash

STACK_USER="stack"
STACK_PASS="stack"
GIT_DIR="/git"
STACK_DIR="${GIT_DIR}/devstack"
ADMIN_PASSWORD="secret"
SCRIPT_DIR=`dirname ${0}`

function transformFile {
  SOURCE="${1}"
  TARGET="${2}"

  sed \
    -e "s|%ADMIN_PASSWORD%|${ADMIN_PASSWORD}|g" \
    "${SOURCE}" > "${TARGET}"
}


echo "This script prepares a system for running devstack"
echo "it assumes that the node is running Ubuntu 1[46].04"
echo

#
# Setup the stack user, needs to be done as root
#
echo "Checking to see if user:${STACK_USER} exists"
cat /etc/passwd | grep '^stack:'
if [ $? -eq 1 ]; then
   echo "Creating user: ${STACK_USER}"
   CRYPTED_PASS=`echo ${STACK_PASS} | openssl passwd -crypt -stdin`
   useradd -d /home/${STACK_USER} -m ${STACK_USER} -p ${CRYPTED_PASS} -s /bin/bash
fi

echo "Checking to see if sudoers file for ${STACK_USER} exists"
if [ ! -f /etc/sudoers.d/${STACK_USER} ]; then
   echo "Creating sudoers file"
   echo "${STACK_USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/${STACK_USER}
fi

echo "Checking to see if the directory:${GIT_DIR} exists"
if [ ! -d "${GIT_DIR}" ]; then
   echo "Creating the base git directory"
   mkdir -p "${GIT_DIR}"
   chown -R ${STACK_USER} "${GIT_DIR}"
fi


# clone the repo
echo "Checking to see if the devstack repo exists"
if [ ! -d "${STACK_DIR}" ]; then
  echo "Cloning the devstack repo"
  git clone https://git.openstack.org/openstack-dev/devstack "${STACK_DIR}"
fi

# create the local configuration files
for F in "local.conf"; do
  echo "Checking to see if the file:${F} file exists"
  if [ ! -f "${STACK_DIR}/${F}" ]; then
    echo "Creating ${F}"
    transformFile "${SCRIPT_DIR}/${F}" "${STACK_DIR}/${F}"
  fi
done

# make sure it's all owned by the right user
chown -R ${STACK_USER} "${STACK_DIR}"

echo "You should now be able to 'su' to ${STACK_USER} and run ${STACK_DIR}/devstack/stack.sh"
